### ISSUE TITLE
Icons showing at the center of the screen

### ISSUE THREAD

**Issue by Razer0123** [MartinPL/Tray-Icons-Reloaded#1]
Simple issue, they should be at the right, they are at the center of the screen instead

Not sure if this is a bug considering you did not add position settings

**Comment by ato10** [comment]
If you use dash to panel you have to change the setting "taskbar position"

**Comment by Razer0123** [comment]
Not using dashtopanel, just normal menubar

**Comment by MartinPL** [comment]
In next release i will set default to right, with option to change.

**Comment by MartinPL** [comment]
fix in 0.6

**Comment by Razer0123** [comment]
Any chance you could also display every icon like status kindicator?

**Comment by MartinPL** [comment]
What do you mean?

**Comment by Razer0123** [comment]
> What do you mean?

Nevermind about the previous issue, but just noticed if i click on radeonprofile  icon, it opens multiples instances instead of showing the window
