### ISSUE TITLE
Webcord / Electron new tray icon implementation not working

### ISSUE THREAD

**Issue by aleksasiriski** [MartinPL/Tray-Icons-Reloaded#103]
**Describe the bug**
Webcord / Electron new tray icon implementation not working, works on `AppIndicator & KStatusNotifierItem Support`

**Desktop (please complete the following information):**
 - Distro: Fedora Silverblue
 - GNOME Shell: 43.1
 - Extension version: 26
 - Display server: Wayland

 I read the compatibility note: [✓]

https://github.com/SpacingBat3/WebCord/issues/329#issuecomment-1337896616

**Comment by Neubulae** [comment]
This problem persists for other Electron apps at least for me

**Comment by aleksasiriski** [comment]
Sadly the dev isn't active. I since switched to `AppIndicator and KStatusNotifierItem Support`

**Comment by Neubulae** [comment]
> Sadly the dev isn't active. I since switched to `AppIndicator and KStatusNotifierItem Support`

I've read some electron release notes, you can switch to the latest electron23 beta to mitigate this issue. I do not know whether it is available on Fedora so you might need npm to do so.

**Comment by aleksasiriski** [comment]
> > Sadly the dev isn't active. I since switched to `AppIndicator and KStatusNotifierItem Support`
> 
> I've read some electron release notes, you can switch to the latest electron23 beta to mitigate this issue. I do not know whether it is available on Fedora so you might need npm to do so.

Eh, I don't want to use beta's on my host OS and flatpak's would need for maintaners to change to beta..

AppIndicator just works

**Comment by Neubulae** [comment]
> > > Sadly the dev isn't active. I since switched to `AppIndicator and KStatusNotifierItem Support`
> > 
> > 
> > I've read some electron release notes, you can switch to the latest electron23 beta to mitigate this issue. I do not know whether it is available on Fedora so you might need npm to do so.
> 
> Eh, I don't want to use beta's on my host OS and flatpak's would need for maintaners to change to beta..
> 
> AppIndicator just works

alright. I have some issues with Appindicator, notably some applications' tray icons leak memory… I have to get them sorted before switching, before that I will stay.
