### ISSUE TITLE
Jetbrains Toolbox doesn't appear on tray

### ISSUE THREAD

**Issue by noriban** [MartinPL/Tray-Icons-Reloaded#107]
**Describe the bug**
Jetbrains toolbox doesn't appear as tray icon. 

https://www.jetbrains.com/toolbox-app/

**Screenshots**

![image](https://user-images.githubusercontent.com/63416481/211158650-59cffa0a-bada-4bcd-89a6-813b58657d75.png)

**Desktop (please complete the following information):**
 - Distro: fedora 37, linux kernel: 6.0.16-300.fc37.x86_64 
 - GNOME Shell: 43.2
 - Extension version: latest on extension market
 - Display server: wayland

 I read the compatibility note: [✓]

**Comment by tybor** [comment]
Other applications does not show their icons when using Wayland display server.
As far as I can say NextCloud, Variety icons are not shown when using Wayland while they are corretcly shown when using X11.
On notable exception is Telegram's icon which shows up in both display servers

**Comment by christopherredden** [comment]
> Other applications does not show their icons when using Wayland display server. As far as I can say NextCloud, Variety icons are not shown when using Wayland while they are corretcly shown when using X11. On notable exception is Telegram's icon which shows up in both display servers

I have the same issue with Jetbrains Toolbox when using X11.

Distro: Ubuntu 22.10, kernel 6.1.12-060112-generic
GNOME Shell: 43
Extension version: latest on extension market
Display server: x11
