### ISSUE TITLE
Gnome 44.1 Tray icons have black background

### ISSUE THREAD

**Issue by sthomas727** [MartinPL/Tray-Icons-Reloaded#120]
Ever since my upgrade to GNOME 44.1, this issue has occurred.
I am running extension version 27, which is the latest version available to me. This was installed through the GNOME extension website.
I have attached images showing the issue I am referring to.
![Screenshot from 2023-05-08 19-06-53](https://user-images.githubusercontent.com/80621180/236785102-cdef259b-a135-44c1-9aba-f06c2d951e0d.png)

**Comment by bbrx94** [comment]
Hello, 
Yes I confirm the same problem on Arch linux with latest version
![image](https://user-images.githubusercontent.com/107874456/236790019-1cbecd0f-8e17-4eba-a928-5fc80189d5ba.png)

![image](https://user-images.githubusercontent.com/107874456/236789911-06f58b79-2f29-4515-924a-c91b4e3a7361.png)

Thanks you for your help ;)

**Comment by vialrogo** [comment]
Same here. How we can help?

**Comment by gzpr** [comment]
It's a gnome [issue](https://github.com/hardpixel/unite-shell/issues/327#issuecomment-1537540322).

**Comment by vialrogo** [comment]
ok, thanks @gzpr. But, that means that it will be stay broken. If gnome devs cosider system tray deprecated, and they are changing things, for they this is not a issue, is a side effect for people using things wrong. hehehe I think the issue can be closed.

**Comment by T0kyoB0y** [comment]
sad:(

**Comment by martinpl** [comment]
Duplicate #114
