### ISSUE TITLE
Slows startup and annoys Dash to dock

### ISSUE THREAD

**Issue by IvanDeFelice76** [martinpl/tray-icons-reloaded#13]
It seems to annoy at boot "Dash to dock" which shrinks and enlarges after a few moments after boot, hopefully it will resolve soon because it is a great extension.

**Comment by IvanDeFelice76** [comment]
At the moment I'm removing it, I'm waiting for updates...

Causes a few hiccups with other widely used extensions.

**Comment by martinpl** [comment]
Can you record how this looks like?
Very weird since this extension don't even interact with dock.
