### ISSUE TITLE
Release tags missing

### ISSUE THREAD

**Issue by Eeems** [MartinPL/Tray-Icons-Reloaded#130]
The last tag for this repo is for version 24, but we are currently on version 29. Are you no longer interested in tagging release versions?

**Comment by Eeems** [comment]
@MartinPL poke?

**Comment by martinpl** [comment]
I will try tag next releases, why this is needed?

**Comment by Eeems** [comment]
> I will try tag next releases, why this is needed?

https://aur.archlinux.org/packages/gnome-shell-extension-tray-icons-reloaded

It's much harder to know if there is a new release right now, plus pointing at a tag instead of a commit hash is simpler to work with.
