### ISSUE TITLE
Adding contrast, saturation, brightness

### ISSUE THREAD

**Issue by sojusnik** [martinpl/tray-icons-reloaded#14]
In order to match the monochrome look of Gnome's tray icons, it would help if you could add some settings to tweak the tray's contrast, saturation and brightness, like already implemented in [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) and [TopIcons Redux](https://extensions.gnome.org/extension/1497/topicons-redux/).

**Comment by martinpl** [comment]
Soon in extensions.gnome.org
