### ISSUE TITLE
ERROR on last version

### ISSUE THREAD

**Issue by KibaGasteiz** [martinpl/tray-icons-reloaded#15]
Using ArchLinux, but people with Fedora having the issue too: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
If you need additional information tell me what to do ;)

**Comment by martinpl** [comment]
Hmmm, did you try ALT + F2, or system restart?

**Comment by KibaGasteiz** [comment]
Okay, seems like restarting fixed it, at least it doesn't appear as update available now.
I don't have an account on extensions.gnome, so i can't write a comment there to tell people the extension is not broken.
Thanks for the fast reply my friend.
