### ISSUE TITLE
Increased CPU usage with Hide Top Bar

### ISSUE THREAD

**Issue by ashucg** [martinpl/tray-icons-reloaded#16]
First of all, thank you for the work you are doing! I really like this extension but I am getting issues when I using it with [Hide Top Bar](https://github.com/mlutfy/hidetopbar) extension. For some reason when I move my cursor to the edge of the screen in order to see the top bar, CPU usage increases and after some time it causes some lag. And today I just upgraded to the latest version and after that GNOME was lagging a lot, making it difficult to use. I had to go back to [TopIconsPlus](https://github.com/phocean/TopIcons-plus), it seems to work fine with Hide Top Bar and doesn't cause any issues for me. Can you please take a look at this issue?

**Comment by martinpl** [comment]
Could you try master (https://github.com/MartinPL/Tray-Icons-Reloaded/archive/master.zip)?

**Comment by ashucg** [comment]
It seems to be much better now, I am no longer getting high CPU usage, thank you! I will continue using master branch code for few hours and I will comment my experience. Thanks again for your work!

**Comment by ashucg** [comment]
I believe this issue has been resolved :tada: I am no longer facing any issues :smile:

**Comment by martinpl** [comment]
I will soon upload it to extensions.gnome.org
