### ISSUE TITLE
Chrome icons

### ISSUE THREAD

**Issue by ato10** [MartinPL/Tray-Icons-Reloaded#2]
![chrome](https://user-images.githubusercontent.com/1146231/78646415-4fb89080-78b9-11ea-9c9a-16dae40b0443.png)

The little 3 pixel green icon is google chrome

**Comment by MartinPL** [comment]
Do you have any tips how to enable tray icon in Chrome, i have enable running in background but icon doesn't even try to create. On KStatus same efect. 

(google-chrome  80.0.3987.163 on Arch)

**Comment by MartinPL** [comment]
Will be fixed in next release.

**Comment by MartinPL** [comment]
fix in 0.6, unfortunately apps with multi trays can't use full features from extensions
