### ISSUE TITLE
Some icons practically invisible.

### ISSUE THREAD

**Issue by shrisha108** [martinpl/tray-icons-reloaded#25]
Hi, First of all thank you so much for a great addon. Really appreciate you work.
The only problem I'm having that after latest update Telegram and Flameshot icons displays just gray. To see them you need to have your panel white or black anything in between is make them very difficult to see. As I said before of the last update everything was fine. There is may be same problem with others app icons but so far for me only this two give this trouble. 
Thank you again.
![Screenshot from 2021-01-13 20-53-58](https://user-images.githubusercontent.com/25418323/104472003-80182280-55e1-11eb-9ee3-855b0533375b.png)
P.S. Interesting that when I receive new message from Telegram then it icon shows notification count it is again become colored as it should be.
I'm on Fedora 33, Gnome 3.38.2, X.org only, coz of Nvidia proprietary drivers :)

**Comment by martinpl** [comment]
Hello, I can't reproduce this issue with that two on similar setup (BTW: Arch Linux, Xorg, Nvidia). Maybe some other extension or theme interfere?

**Comment by shrisha108** [comment]
I'm sorry. This is false report. That's a icons theme what I used. I didn't realized that there is two of them. One for light and one for dark shell theme. So if you apply light theme but with dark shell color then this two icons are dark . And I got dark on dark. :)
Sorry once again. And thank you again for great addon!

**Comment by Hezkore** [comment]
I'm on Ubuntu using the default Yaru (light) theme, and most of my tray icons are white, so it's white on white.
How should I go about making Tray Icons Reloaded use black icons?

![2021-11-23_21-26](https://user-images.githubusercontent.com/1727541/143098773-887dd834-cb7a-4002-8b76-be95ef27ad0c.png)
