### ISSUE TITLE
Telegram icon too small now

### ISSUE THREAD

**Issue by trevarj** [martinpl/tray-icons-reloaded#27]
For some reason the telegram icon is really small now (after recent update to the extension or Gnome)

![image](https://user-images.githubusercontent.com/5448324/107372032-072fbc00-6af6-11eb-8d8a-a4f5778550e3.png)

**Comment by martinpl** [comment]
This doesn't look like Telegram icon, maybe it is icon bundle problem.

**Comment by trevarj** [comment]
Yeah, probably right. Papirus issue
