### ISSUE TITLE
Generic 3 dot icon turned gray

### ISSUE THREAD

**Issue by japkov** [martinpl/tray-icons-reloaded#28]
The generic 3 dot icon that is being shown when *Tray icon limit* is set to 4 and less suddenly turned from white to gray.

This is how it look yesterday: 

![image](https://user-images.githubusercontent.com/69731550/108515307-364be780-72c5-11eb-9aed-068d2591b9ea.png)

This is today:

![image](https://user-images.githubusercontent.com/69731550/108515361-4368d680-72c5-11eb-9681-cf3a5e162d4d.png)

Same customization applies on both screens - Arc-Darker for programs, Ark-Dark for shell and Papirus icon theme. Moreover, it doesn't matter which shell theme or icon set I'll pick - three dots remain gray.

It might be not some big issue but it is kinda annoying.

Also: wielkie dzięki za to rozszrzenie - świetnie się sprawuje ;)

**Comment by ErikSteiner** [comment]
**Dash to Dock** user here, I noticed that, too. After login the three dots are white as expected, but they turn dark grey when you move over it with the mouse. Then they remain dark grey.

**Comment by martinpl** [comment]
Should be fixed on master ;)
