### ISSUE TITLE
Adding backward compatibility for settings shows an obscure error.

### ISSUE THREAD

**Issue by Poikilos** [martinpl/tray-icons-reloaded#29]
I added backward compatibility code from <https://github.com/negesti/gnome-shell-extensions-negesti/commit/34df1802bbf6e01b4d7931befce71f950a9e0401> because I am using Debian 10 Buster which is on GNOME 3.30 forever.
- I can't tell for sure if the commit name < is a typo and they mean <= 3.30!

Can you take a look at this and see if you can fix it? I don't understand the error "`Missing variable name`" --the error only references the core (files in /usr not in `~/.local/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl`)
[trayIconsReloaded-Poikilos-patched-try1.tar.gz](https://github.com/MartinPL/Tray-Icons-Reloaded/files/6079746/trayIconsReloaded-Poikilos-patched-try1.tar.gz)

I went back to trayIconsReloadedselfmade.pl.v9.shell-extension.zip since that was the latest version for GNOME 3.36 but it still doesn't work on GNOME 3.30.2.

**Comment by martinpl** [comment]
Sorry but backward compatibility was never options, if someone wants to maintain branches for old versions feel free to PR.
