### ISSUE TITLE
KStatusNotifierItem support (missing icon on new electron apps)

### ISSUE THREAD

**Issue by beedaddy** [martinpl/tray-icons-reloaded#3]
Maybe it's me and I missed something, but the icon from the Matrix client "Riot" doesn't show up. There's no problem with other icons (nextcloud-client, keepassxc, ...).

I'm using Arch Linux and installed the riot client (riot-desktop). All software is up-to-date (Gnome 3.36.1).

**Comment by martinpl** [comment]
Looks like new Electron apps use only KStatusNotifierItem API. We current don't support this. I will try poke this topic in far future, fix will not happend anytime soon.

**Comment by martinpl** [comment]
There is workaround for this problem :D
https://git.sr.ht/~steef/snixembed
https://aur.archlinux.org/packages/snixembed-git
(for autostart you need add `snixembed --fork` to ~/.profile)
Current it break left click hack.

Kudos for Steef

**Comment by rmeissn** [comment]
I got the same problem described by @beedaddy for nextcloud-client. Using another extension fixed this for me. See this post: https://github.com/nextcloud/desktop/issues/1656#issuecomment-627461413

**Comment by martinpl** [comment]
Like OP said nextcloud-client works fine here, but anyway with next release i will recommend using snixembed for this issue (KStatusNotifierItem support). Qt apps like nextcloud-client should works fine out of box.
