### ISSUE TITLE
TypeError in gnome version 40.0

### ISSUE THREAD

**Issue by Ali-Nazarii** [martinpl/tray-icons-reloaded#30]
TypeError: widgets.show_all is not a function

Stack trace:
  buildPrefsWidget@/usr/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl/prefs.js:141:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by martinpl** [comment]
You need to update to the newest release :P
