### ISSUE TITLE
Programs that have tray support are unable to use the tray in wayland sessions.

### ISSUE THREAD

**Issue by reisaraujo-miguel** [martinpl/tray-icons-reloaded#37]
I am having problems with two programs, qBittorrent and CopyQ. When I'm in a wayland session, they don't go to the tray, unlike the X11 session.

extension version: 14 (from gnome extensions site)
qBittorrent version: 4.3.4.1 (from Fedora 34 repo)
CopyQ version: v4.1.0 (from Fedora 34 repo)

wayland version: 1.19.0-1 (from Fedora 34 repo)
gnome-session-wayland-session version: 40.1.1-1 (from Fedora 34 repo)
qt5-qtwayland version: 5.15.2-5 (from Fedora 34 repo)
Xwayland version: 21.1.1-1 (from Fedora 34 repo)

**Comment by martinpl** [comment]
You can run these apps through XWayland via command:
`GDK_BACKEND=x11 app_name `
