### ISSUE TITLE
yad --notification does not work as expected

### ISSUE THREAD

**Issue by nicofooo** [martinpl/tray-icons-reloaded#38]
Hello,
the notification sent by yad does not work with your extension:
`yad --notification`
adds well the notifier in the tray zone. But when I click on the icon, it opens the program 'yad-icon-browser' instead of just returning. It is then not possible to remove the yad notifier (unless killing it).

Note: I had no problem with "Tray Icons" extension: https://extensions.gnome.org/extension/1503/tray-icons/
No problem either with KDE Plasma.

**Comment by nicofooo** [comment]
I don't know if the previous commits are supposed to fix the issue, but for me it is not solved using last version from extensions.gnome.com (version 17)

**Comment by martinpl** [comment]
On master should be okey, extensions.gnome.com is not updated yet.

**Comment by nicofooo** [comment]
thank you, it is now updated (version 19) and it works ;)
