### ISSUE TITLE
Feature request: port feature from unite plugin "convert tray icon to greyscale"

### ISSUE THREAD

**Issue by patrick-tang** [martinpl/tray-icons-reloaded#39]
Hi,
This is the exact extension we love: focus on tray and do it well!
Is that possible to port one feature from unite extension?
The feature is: convert tray icon to greyscale
![greyscale in trayicon](https://user-images.githubusercontent.com/40742640/118375095-8b7a5b00-b58d-11eb-9a48-da8c51956bf6.png)

**Comment by martinpl** [comment]
Hello, 
This feature is available under 'saturation' name ;)

**Comment by patrick-tang** [comment]
Appologize,  I didn't know. :(
Thanks, Marcin.

**Comment by patrick-tang** [comment]
Hi @MartinPL , seems the "icon saturation" has no effect. By default it is 0, but all icons are still colorful.
With unite extension, when select greyscale, icons in tray will be white/black only so match other gnome
 tray icons. Screenshot when Saturation is 0 but still with colorful icons (![tray icon reload](https://user-images.githubusercontent.com/40742640/118516476-57757600-b704-11eb-9ed9-af13fe9d4ba4.png)
)

**Comment by martinpl** [comment]
It should be set to 100, if still don't work try restart app.

**Comment by Flying--Dutchman** [comment]
Facing the same issue. Icon saturation is set to 100 but the icons are still colored.

EDIT:
Appearantly incompatible with Unite. Having both of them, unite and tray icons reloaded, active caused this issue for me.
Toggling Unite off and on again fixed it for me for now.
