### ISSUE TITLE
Icon spacing

### ISSUE THREAD

**Issue by codedmart** [martinpl/tray-icons-reloaded#4]
Is it possible or could it be added to the config to be able to adjust the spacing between the tray icons?

**Comment by martinpl** [comment]
I will add this option in next release.

**Comment by codedmart** [comment]
Thank you!

**Comment by martinpl** [comment]
Soon in extensions.gnome.org

**Comment by codedmart** [comment]
Figured I would ask here instead of opening a new issue since it relates to it. Is it possible to get the spacing smaller then 0? The tray icons even with config at 0 still are more spaces then the rest of my gnome panel icons.

![Panel](https://user-images.githubusercontent.com/40686/118494659-a4932100-b6df-11eb-9491-4abfd6bc126a.png)
![CaffeineHover](https://user-images.githubusercontent.com/40686/118494661-a52bb780-b6df-11eb-91fa-bb081088d077.png)
![TrayHover](https://user-images.githubusercontent.com/40686/118494663-a52bb780-b6df-11eb-92d5-d43edfc2f73b.png)

Thanks
