### ISSUE TITLE
Duplicated icons and bugs with Cpod

### ISSUE THREAD

**Issue by rysete** [martinpl/tray-icons-reloaded#41]
I used in Cpod flatpak version and the left click don't open the app and duplicate if I try relaunch the app.

**Comment by martinpl** [comment]
Can't reproduce on Arch. What distro do you use and what version of flatpak?

**Comment by rysete** [comment]
I'm using Fedora 34 and flatpak 1.10.2, I've tested it with a Appimage version (1.27.1) and it has the same behavior.
