### ISSUE TITLE
Some status icons are missing on wayland, but are shown correctly when running gnome on xorg

### ISSUE THREAD

**Issue by jfinas** [martinpl/tray-icons-reloaded#43]
In my case specifically the tray icon of syncthing-gtk and solaar.
The [AppIndicator and KStatusNotifierItem Support Extension](https://extensions.gnome.org/extension/615/appindicator-support/) is showing the missing icons correctly under wayland(however it is missing other icons).
I would guess this is due to both being using native wayland, so maybe this is not an issue since the README says this extension only supports xwayland...

Gnome Version: 40.2.0
Extension Version: 14
Distro: Arch

**Comment by martinpl** [comment]
Exactly, they're using pure Wayland. You can bring them back by using command: 
`GDK_BACKEND=x11 app_name`

**Comment by InklingGirl** [comment]
I'm sorry for bumping this @MartinPL, but may you please elaborate? What is using 'pure Wayland' & how is that affecting this? I'm also having this issue, i.e. different icons missing in different tray extensions. Thank you.
