### ISSUE TITLE
Cannot install newest version

### ISSUE THREAD

**Issue by stephanschindel** [martinpl/tray-icons-reloaded#49]
Hi,

since latest upgrade I cannot install the extension anymore. I tried removing and reinstalling it completely, did not work.

GNOME: 40.1.0
OS: Fedora 34

**Comment by slobo** [comment]
Same here, wish I didn't hit the update button :(

**Comment by martinpl** [comment]
Try to remove it manually from ```/home/YOURNAME/.local/share/gnome-shell/extensions/shell-reloaded@selfmade.pl```
You can do it from terminal via ```rm -r /home/YOURNAME/.local/share/gnome-shell/extensions/shell-reloaded@selfmade.pl```
Restart PC and install again.
