### ISSUE TITLE
Extension (v 4) error

### ISSUE THREAD

**Issue by kenny3794** [martinpl/tray-icons-reloaded#5]
Upgrading from v3 to v4 from the Gnome Extensions website caused the extension to fail to load after reboot.  The output of journalctl shows the following error:

`ERROR: Extension trayIconsReloaded@selfmade.pl: GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl/schema/gschemas.compiled”: open() failed: No such file or directory
`

Changing the `schemas` director to `schema` seems to fix the issue locally.  It looks like this folder name was changed recently.

**Comment by kenny3794** [comment]
Nevermind. This error is specific to upgrading from v3 to v4 and not logging out.  Once Logged out and logged back in, the error goes away.   Sorry for the false report.

**Comment by martinpl** [comment]
I was wondering what was going on, thanks for info :D
