### ISSUE TITLE
Unnecessary margin and padding of icons

### ISSUE THREAD

**Issue by Mariyo** [martinpl/tray-icons-reloaded#54]
Hello,

is it possible to optimize margin and padding of icons? 

![image](https://user-images.githubusercontent.com/1678254/132556276-a7c8d9c3-eaa6-44cf-955c-a928b0c498d3.png)

Thank you

**Comment by martinpl** [comment]
:wave: 
Padding and margin can be change in settings, pick what the best suit to you.

**Comment by Mariyo** [comment]
@MartinPL i am a bit confused, which settings? Does this extension have own settings? How to find them?

Thank you

**Comment by martinpl** [comment]
To acess setting you need to install Extensions app or GNOME Tweaks
