### ISSUE TITLE
qbittorrent, vivaldi icons look blank

### ISSUE THREAD

**Issue by kwon37xi** [MartinPL/Tray-Icons-Reloaded#57]
qbittorrent and vivaldi system tray icon look blank.
![image](https://user-images.githubusercontent.com/545649/135944370-71ae96e2-d606-4bda-8c8a-c606f1e69c08.png)

**Comment by martinpl** [comment]
I can't reproduce with qBittorrent, with Vivaldi i'm not sure how to enable tray icon :man_shrugging: 
![image](https://user-images.githubusercontent.com/8329810/145724235-c1a70787-0827-4b58-b291-2a8a8f5ab53d.png)

**Comment by kwon37xi** [comment]
1. ubuntu 21.10's qbittorrent tray icon does not appear. but the latest version of qbittorrent tray icon is ok.
2. Actually I also don't know how to enabled vivaldi's tray icon. (sometimes it appears, but usually does not appear).

I think this issue is better to be closed.
