### ISSUE TITLE
Working with app indicator?

### ISSUE THREAD

**Issue by changemenemo** [MartinPL/Tray-Icons-Reloaded#59]
It seems that every changes your app make is overwritten by appindicator. 
When this extension is activated, yours don't limit it the icons of it...

**Comment by martinpl** [comment]
You mean by [that](https://github.com/ubuntu/gnome-shell-extension-appindicator)? If yes it is definitely not compatible, I shoulde make a note about that in readme.

**Comment by changemenemo** [comment]
Yeah because I need it to display some of the icons that you addon doesn't display
