### ISSUE TITLE
variety icon not diplaying

### ISSUE THREAD

**Issue by changemenemo** [MartinPL/Tray-Icons-Reloaded#63]
variety icon not displaying
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
PRETTY_NAME="Ubuntu 21.10"
under wayland
extension release 16

**Comment by martinpl** [comment]
https://github.com/MartinPL/Tray-Icons-Reloaded#wayland
