### ISSUE TITLE
portmaster icon not displaying

### ISSUE THREAD

**Issue by changemenemo** [MartinPL/Tray-Icons-Reloaded#64]
portmaster firewall tray notifier is not displaying
https://github.com/safing/portmaster/

DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
PRETTY_NAME="Ubuntu 21.10"
GNOME Shell 40.5
under wayland
extension release 16

**Comment by martinpl** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/8329810/154325307-053fe85c-231a-4f66-b943-907feb3f9e33.png)

So there are few possibilities:
1) Issue is aready fixed
1) Try to run it via XWayland (`GDK_BACKEND=x11 app_name`)
1) Missing dependencies https://github.com/safing/portmaster-ui/tree/develop/notifier
2) Whole icon need to be run separately `/opt/safing/portmaster/portmaster-start notifier`

**Comment by changemenemo** [comment]
> Works fine on my end.
> 
> ![image](https://user-images.githubusercontent.com/8329810/154325307-053fe85c-231a-4f66-b943-907feb3f9e33.png)
> 
> 
> 
> So there are few possibilities:
> 
> 1) Issue is aready fixed
> 
> 1) Try to run it via XWayland (`GDK_BACKEND=x11 app_name`)
> 
> 1) Missing dependencies https://github.com/safing/portmaster-ui/tree/develop/notifier
> 
> 2) Whole icon need to be run separately `/opt/safing/portmaster/portmaster-start notifier`

I think because of the several iteration of this soft in the last 2 months it has been resolved over time. Thanks 🙏
