### ISSUE TITLE
Not working, 3 dots visible but icons still show in taskbar

### ISSUE THREAD

**Issue by NayamAmarshe** [MartinPL/Tray-Icons-Reloaded#65]
![image](https://user-images.githubusercontent.com/25067102/146672912-1d0fc1f8-29b0-445f-89e8-13aef68750db.png)

I'm on ZorinOS Gnome 3.38.4. ZorinOS uses Dash to Panel for the taskbar. The three dots do appear on clicking it, it shows a reminder icon and nothing else. Other apps like Telegram, Barrier with tray icons don't appear inside the Tray Icons Reloaded container. I've set my tray size to just 1.

Can this be fixed? or is it just incompatible?

**Comment by martinpl** [comment]
I'm not familiar with Zorin OS but looks like they ship own extension for tray icons, try to disable it before. (gnome-shell-extension-zorin-appindicator)

**Comment by NayamAmarshe** [comment]
> I'm not familiar with Zorin OS but looks like they ship own extension for tray icons, try to disable it before. (gnome-shell-extension-zorin-appindicator)

Thanks! I had to turn off the Zorin Appindicator extension and Tray Icons Reloaded now works fine :D
