### ISSUE TITLE
Cannot set Icon saturation to 100 anymore

### ISSUE THREAD

**Issue by snarkyalyx** [MartinPL/Tray-Icons-Reloaded#69]
I'm unable to set Colors -> Icon saturation to 100. Before, I did that so that my tray icons are all black and white so that it fits into the UI more unifed.

**Comment by szobi** [comment]
Me too... The maximum is 80 now, but was 100 before.

**Comment by snarkyalyx** [comment]
@MartinPL  You closed this with no response and def6b3d didn't fix anything. You only made the user able to type in 100, but it hard-limits to 80. Take a look, the icons still have color, and if you press ¨-" it goes back to 70 instead of 90.,

**Comment by martinpl** [comment]
@Awoolyx Are using version from GitHub / master? GE wasn't updated yet.
