### ISSUE TITLE
No right click menu

### ISSUE THREAD

**Issue by changemenemo** [MartinPL/Tray-Icons-Reloaded#78]
**Describe the bug**
Concerns last update of yesterday, the right click menu does not work anymore. 
Test with variety or Rocket.chat in flatpak for example or element etc. Everything that relies on the system to print a menu and does not have its own menu integrated 
**Screenshots**

**Desktop (please complete the following information):**
 - Distro: fedora 35
 - GNOME Shell: 41.3
 - Extension version: 20
 - Display server: x11

 I read the compatibility note: [✓]

**Comment by Lalilalulalam** [comment]
I can confirm same behavior using EndeavourOS with same parameters as above.
Right click works only when icons are not packed in tray (set high apps limit).

**Comment by changemenemo** [comment]
Good to know I didn't try that since it s always in a tray on my end.

**Comment by palexdev** [comment]
Yes, last update broke context menu
Is it possible to downgrade the extension? After all the last update not only is buggy but is useless too
I mean, we need one and only fix which is #42 and still nothing

**Comment by martinpl** [comment]
Stupid mistake, I will make hot fix today.

**Comment by dmytro-shchurov** [comment]
I think the same reason is for a "lost focus" issue. If I **left** click on, for instance, a Flameshot icon in the tray, the next thing I expect is a cross mouse cursor, and a mouse ready to select some area on a screen. Instead, I have to click on a screen first to get that state with a cross mouse cursor.

**Comment by martinpl** [comment]
@dmytro-shchurov open another issue if this bug still exist
