### ISSUE TITLE
Gnome 42 Error For settings

### ISSUE THREAD

**Issue by ryzendew** [MartinPL/Tray-Icons-Reloaded#83]
**Describe the bug**
A clear and concise description of what the bug is, steps to reproduce the behavior if possible.

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: Fedora 36 Beta 1.1
 - GNOME Shell: 42
 - Extension version: 21
 - Display server: Wayland

 I read the compatibility note: [✓]

Using Gnome 42 beta the Extension works Fine minus the Settings window.

`Error: set_titlebar() is not supported for Adw.Window
  Stack trace:
  set_titlebar/<@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:51:17
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:21:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by iWeaker** [comment]
Go to $HOME/.local/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl/preferences/Pref.js and remove window.set_titlebar(this._headerBar); , reload your gnome session and try again, i did a pull request to fix that

**Comment by ryzendew** [comment]
Thanks

**Comment by martinpl** [comment]
Fixed in v23.
