### ISSUE TITLE
gtrayicon's icon does not show up

### ISSUE THREAD

**Issue by jose1711** [MartinPL/Tray-Icons-Reloaded#85]
**Describe the bug**
  * install `gtrayicon` (http://gtrayicon.sourceforge.net/) from AUR
  * run `gtrayicon --activate=xterm --deactivate=xterm --activated`
  * icon should show up in the tray area but nothing appears there

**Screenshots**
n/a (nothing to show)

**Desktop (please complete the following information):**
 - Distro: Arch Linux
 - GNOME Shell: 41.4-1
 - Extension version: 21
 - Display server: X11

 I read the compatibility note: [✓]

**Comment by martinpl** [comment]
![image](https://user-images.githubusercontent.com/8329810/158554368-dfba9eed-97c5-4656-98a8-6c5b715a4d2c.png)
Works on my side. Maybe some missing deps, lib32-libappindicator-gtk2?

**Comment by jose1711** [comment]
Hmm, it started to work after the latest update. Everything working great in version 22. Thanks.
