### ISSUE TITLE
Impelement overflow

### ISSUE THREAD

**Issue by ripefig** [martinpl/tray-icons-reloaded#9]
Most systray implementations have an overflow menu, so that not all icons are necessarily shown on the panel.

I think it might be useful to have an option to put all icons into an overflow, for people who need these icons only occasionally and don't really want to see random icons in the panel at all times.

(another alternative to crowding up the top panel with icons is to move the tray entirely to the activities overview. This would also give you more space to work with, so one could make the click targets bigger, thereby improving the usability of the tray.)

**Comment by martinpl** [comment]
Pre-release is ready to test.
Two UX thing:
- popup must be close on right click,
- overflow mode don't change right after updated setting,

 https://github.com/MartinPL/Tray-Icons-Reloaded/releases/tag/0.6.9

**Comment by ripefig** [comment]
Have you considered sticking the tray into the overview? Seems like the only logical option for Gnome Desktop, since that's where all the apps are. 

No random clutter in the panel, no hidden popups ... and you could finally get around the main problem with systrays, which is tiny click targets. What do you think @MartinPL?

**Comment by martinpl** [comment]
Current i will move my focus to another projects, but you can leave mockups how you see it.
