### ISSUE TITLE
Version 24 not available on GNOME Shell Extensions Website

### ISSUE THREAD

**Issue by dstolpmann** [MartinPL/Tray-Icons-Reloaded#91]
Hi,
thank you for accepting my pull request #90. I have seen that you released version 24 of the extension on GitHub. However, I still get version 23 via the GNOME Shell Extensions website. Did you miss do upload the new version there or is it still stuck in a review process?

Best regards,
Daniel

**Comment by martinpl** [comment]
Version 24 got rejected due to the old review notice, new version waiting for check.

**Comment by dstolpmann** [comment]
I just got the update to version 25 (which is not tagged on GitHub). Thank you!
