### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by leukimi** [MartinPL/Tray-Icons-Reloaded#92]
DELETED

**Comment by agschwind** [comment]
I can confirm the same problem on Fedora 36

**Comment by RomanAverin** [comment]
On Gnome Extension site available ver. 25 working well Fedora 36, Gnome 42

**Comment by RomanAverin** [comment]
> > On Gnome Extension site available ver. 25 working well Fedora 36, Gnome 42
> 
> @RomanAverin How did you make it work? Please share. I can't get it to work yet. Tried version 23, 24, 25 and still no success. I even added the app manualy via the plus sign, still no change.

My GNOME version 42.1

**Comment by forward32** [comment]
It does not work on ArchLinux with Gnome 42.2 too. Do you have any planes to fix it @MartinPL?

**Comment by martinpl** [comment]
@forward32 It works fine on my Arch instance, so I would say Wayland issue or missing deps.

**Comment by forward32** [comment]
@MartinPL I use X11 on my Arch installation. Everything was fine until today when I updated the system and got Gnome 42.2. So now trying to turn on this extension I'm getting the following error:
```
Error: set_titlebar() is not supported for Adw.Window

Stack trace:
  set_titlebar/<@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:51:17
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by martinpl** [comment]
@forward32 update also extension :P

**Comment by forward32** [comment]
Oooh, my fault, sorry for disturbing! Now it works fine on Arch + Gnome 42.2 :+1:

**Comment by HenriWahl** [comment]
> > On Gnome Extension site available ver. 25 working well Fedora 36, Gnome 42
> 
> @RomanAverin How did you make it work? Please share. I can't get it to work yet. Tried version 23, 24, 25 and still no success. I even added the app manualy via the plus sign, still no change.

Same here :-(

**Comment by caseyamcl** [comment]
I had the same problem, but I fixed it by downloading the standalone "Extension Manager" from the software app and turning the toggle switch on the title bar to the "on" position.
